Changes to shape objects to explicitly set opaque property when changing colors
adafruit/Adafruit_CircuitPython_Display_Shapes pull request #8
Opened 2019-10-30 23:14 UTC by DavePutz

When a shapes color or transparency is being changed the proper transparent or opaque properties need to be changed in case it is going from a transparent to opaque state (or vice-versa). Also, in the roundrect __init__ the chunk needs to be drawn even if the initial fill is None; otherwise there seems to be nothing to change the color of later on.

2019-10-31 16:10 UTC, makermelissa requested changes
Just a minor change needed for Travis to pass. Have you tested this or do you have any code for testing this out? Thanks

2019-10-31 16:10 UTC, makermelissa commented on adafruit_display_shapes/roundrect.py
> +                    x_offset=width-2*r-1, y_offset=height-2*r-1)
It looks like it failed the checks because a space need to be added to this line.

2019-10-31 18:58 UTC, DavePutz commented
Hi Melissa,

         Thanks for looking at this one. Odd that a space would be missing
since I just cut & pasted
several lines to move the location of the code. Anyway, I fixed it.
The test script that is in the issue to show the problem can also be used
to test that the fix was effective.
There is another script from the submitter for the core issue at
https://github.com/adafruit/circuitpython/issues/2076
Hope this helps,

                                  -Dave




On Thu, Oct 31, 2019 at 11:10 AM Melissa LeBlanc-Williams <
notifications@github.com> wrote:

> *@makermelissa* requested changes on this pull request.
>
> Just a minor change needed for Travis to pass. Have you tested this or do
> you have any code for testing this out? Thanks
> ------------------------------
>
> In adafruit_display_shapes/roundrect.py
> <https://github.com/adafruit/Adafruit_CircuitPython_Display_Shapes/pull/8#discussion_r341230116>
> :
>
> > @@ -65,16 +55,18 @@ def __init__(self, x, y, width, height, r, *, fill=None, outline=None, stroke=1)
>          self._palette = displayio.Palette(3)
>          self._palette.make_transparent(0)
>          self._bitmap = displayio.Bitmap(width, height, 3)
> +        for i in range(0, width):   # draw the center chunk
> +            for j in range(r, height - r):   # draw the center chunk
> +                self._bitmap[i, j] = 2
> +        self._helper(r, r, r, color=2, fill=True,
> +                    x_offset=width-2*r-1, y_offset=height-2*r-1)
>
> It looks like it failed the checks because a space need to be added to
> this line.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/adafruit/Adafruit_CircuitPython_Display_Shapes/pull/8?email_source=notifications&email_token=AFNJKERYUPQDHURGHBKPR3TQRL7PXA5CNFSM4JHBTW22YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCJ5ECKQ#pullrequestreview-310001962>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFNJKETO2DA6DWPX3OS3DA3QRL7PXANCNFSM4JHBTW2Q>
> .
>

2019-10-31 19:20 UTC, makermelissa commented
Ok, awesome. I will test this later today.

2019-11-01 00:06 UTC, makermelissa approved these changes
Tested before and after changes and I could see the effect. Tested in both CP 4 and 5.

2019-11-01 00:07 UTC, merged

2019-11-01 00:07 UTC, makermelissa commented
Thanks for adding this!

2019-11-01 22:31 UTC, jpecor commented
Thanks for the fix to this issue!  I haven't had a chance to test it with the original project where I ran across the problem, but I hope to do that this weekend.

2019-11-02 00:01 UTC, tannewt reviewed
Thanks for this @DavePutz ! One comment about a comment but looks good otherwise. Thanks!

2019-11-02 00:01 UTC, tannewt commented on adafruit_display_shapes/roundrect.py
> +an explicit call to palette.make_opaque() in the fill color setter function.
This is no longer true. It should document what a roundrect is.